name: release

on:
  push: 
    tags:
      - '*'
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true
      SECRET_KEY:
        required: true
      DEBUG:
        required: true
permissions:
  contents: write

jobs:
  buildTest:
    uses: decide-part-alberti-2/decide-part-alberti-2/.github/workflows/django.yml@master
    secrets: 
      CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DEBUG: ${{secrets.DEBUG}}
     
  release:
    needs: buildTest
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo SECRET_KEY="${{ secrets.SECRET_KEY }}"
          echo DEBUG="${{ secrets.DEBUG }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
